manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      remote: nordic
      revision: ff710e16cd45c253a77b00c2d8fb39e006b6a19d
      import: true
  self:
    path: firmware
