manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: sigvartmh
      url-base: https://github.com/sigvartmh
  projects:
    - name: fw-nrfconnect-nrf-1
      path: nrf
      remote: sigvartmh
      revision: fix/aws-fota-failure
      import: true
  self:
    path: firmware
