manifest:
  remotes:
    - name: nordic
      url-base: https://github.com/NordicPlayground
  projects:
    - name: fw-nrfconnect-nrf
      path: nrf
      remote: nordic
      revision: ad37f4dec7b442240035db2b78e9d09addce2794
      import: true
  self:
    path: firmware
