name: Verify Dockerfile

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build -t bifravst-firmware-docker .

      - name: Configure the AWS IoT broker hostname
        run: echo "CONFIG_AWS_IOT_BROKER_HOST_NAME=\"example.com\"" >> prj.conf

      - name: Build for Thingy:91
        run: |
          docker run --rm -v ${PWD}:/workdir/ncs/firmware bifravst-firmware-docker /bin/bash -c 'cd ncs/firmware; west build -p always -b nrf9160_pca20035ns'
          ls -la build/zephyr/merged.hex

      - name: Build for 9160 DK
        run: |
          docker run --rm -v ${PWD}:/workdir/ncs/firmware bifravst-firmware-docker /bin/bash -c 'cd ncs/firmware; west build -p always -b nrf9160_pca10090ns'
          ls -la build/zephyr/merged.hex
